Take in command line options

diff --git a/insomnia-lite b/insomnia-lite
--- a/insomnia-lite
+++ b/insomnia-lite
@@ -12,5 +12,21 @@ function showRestNotification()
 declare -a sleepTimes
 
 
-
-showRestNotification
+while getopts ":ts::" opt; do
+  case $opt in
+    s)
+      echo "-s was triggered, Parameter: $OPTARG" >&2
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    t)
+      showRestNotification
+    ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
