Check For Active Internet Connection On Update
Don't tell the user they have the latest version if we got no response from the github api

diff --git a/sandman-lite b/sandman-lite
--- a/sandman-lite
+++ b/sandman-lite
@@ -178,6 +178,10 @@ fi
 
 function checkForUpdate()
 {
+  if [[ $(curl -s https://api.github.com/repos/alexanderepstein/Sandman-Lite/tags) == "" ]];then
+    echo "Error: no active internet connection"
+    exit 1
+  fi
   latestVersion=$(curl -s https://api.github.com/repos/alexanderepstein/Sandman-Lite/tags | grep -Po '"name":.*?[^\\]",'| head -1 | cut -c11-15)
   if [[ "$latestVersion" != "$currentVersion"  && "$latestVersion" != "" ]]; then
     echo "Version $latestVersion available"
